// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAfESHb9xRC7RKW_kyTMvx9x3byxKn2As',
    appId: '1:134633209063:web:063369f0d9790ac506f642',
    messagingSenderId: '134633209063',
    projectId: 'graduation-project-6c1ba',
    authDomain: 'graduation-project-6c1ba.firebaseapp.com',
    storageBucket: 'graduation-project-6c1ba.appspot.com',
    measurementId: 'G-X4X9DW7FFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCFqrJS0fTm-ET294fKX_JIFLpcLCeDIQ',
    appId: '1:134633209063:android:0cc404227b7baee406f642',
    messagingSenderId: '134633209063',
    projectId: 'graduation-project-6c1ba',
    storageBucket: 'graduation-project-6c1ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3oKv02v1xkK2FASn09VRtvagZlQJA1fQ',
    appId: '1:134633209063:ios:cebdb2c8a13a2b9b06f642',
    messagingSenderId: '134633209063',
    projectId: 'graduation-project-6c1ba',
    storageBucket: 'graduation-project-6c1ba.appspot.com',
    iosClientId: '134633209063-lgpdg9l00f468ih5s6po39h5n3br7hf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mowasulatuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3oKv02v1xkK2FASn09VRtvagZlQJA1fQ',
    appId: '1:134633209063:ios:cebdb2c8a13a2b9b06f642',
    messagingSenderId: '134633209063',
    projectId: 'graduation-project-6c1ba',
    storageBucket: 'graduation-project-6c1ba.appspot.com',
    iosClientId: '134633209063-lgpdg9l00f468ih5s6po39h5n3br7hf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mowasulatuna',
  );
}
